config/routes.rb
Rails.application.routes.draw do
  get 'package_trackings/create'

  get 'package_trackings/destroy'

	devise_for :users, controllers: { sessions:      'users/sessions', passwords: 'users/passwords', confirmations: 'users/confirmations',
	                                  registrations: 'users/registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	devise_scope :user do
		get '/users/sign_up/:code', to: 'users/registrations#new', as: :sign_up
		# match '/users/:id', to: 'users/registrations#delete_user', via: :delete, as: :delete_user
	end

	root 'package_trackings#track_package'
	resources :invited_users
	resources :packages
  post 'package_trackings/create/:id', to: 'package_trackings#create', as: :package_trackings
	get 'package_trackings/track_package', to: 'package_trackings#track_package', as: :track_package

end

app/models/invited_user.rb
class InvitedUser < ApplicationRecord
	validates :email, uniqueness: true
	validates :code, uniqueness: true

	after_create :generate_code

	private
	def generate_code
		code         = SecureRandom.urlsafe_base64
		invited_user = InvitedUser.find_by(code: code) if InvitedUser.all.present?
		generate_code if invited_user.present?
		self.code = code
		self.save
	end
end

app/controllers/invited_users_controller.rb
class InvitedUsersController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_permissions
	before_action :set_invited_user, only: [:show, :edit, :update, :destroy]

	# GET /invited_users
	# GET /invited_users.json
	def index
		@invited_users = InvitedUser.all
	end

	# GET /invited_users/1
	# GET /invited_users/1.json
	def show
	end

	# GET /invited_users/new
	def new
		@invited_user = InvitedUser.new
	end

	# GET /invited_users/1/edit
	def edit
	end

	# POST /invited_users
	# POST /invited_users.json
	def create
		@invited_user = InvitedUser.new(invited_user_params)

		respond_to do |format|
			if @invited_user.save
				InvitedUserMailer.invite_email(@invited_user, sign_up_url(@invited_user.code)).deliver_now
				format.html { redirect_to @invited_user, notice: 'Invited user was successfully created.' }
				format.json { render :show, status: :created, location: @invited_user }
			else
				format.html { render :new }
				format.json { render json: @invited_user.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /invited_users/1
	# PATCH/PUT /invited_users/1.json
	def update
		respond_to do |format|
			if @invited_user.update(invited_user_params)
				format.html { redirect_to @invited_user, notice: 'Invited user was successfully updated.' }
				format.json { render :show, status: :ok, location: @invited_user }
			else
				format.html { render :edit }
				format.json { render json: @invited_user.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /invited_users/1
	# DELETE /invited_users/1.json
	def destroy
		@invited_user.destroy
		respond_to do |format|
			format.html { redirect_to invited_users_url, notice: 'Invited user was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
	# Use callbacks to share common setup or constraints between actions.
	def set_invited_user
		@invited_user = InvitedUser.find(params[:id])
	end

	# Never trust parameters from the scary internet, only allow the white list through.
	def invited_user_params
		params.require(:invited_user).permit(:email, :role, :code, :status, :first_name, :last_name)
	end
end

app/helpers/invited_users_helper.rb
module InvitedUsersHelper
end

app/views/invited_users/_form.html.erb
<%= render 'shared/errors', obj: @invited_user %>
<%= form_with(model: invited_user, local: true) do |form| %>

  <div class="col-sm-6">
    <%= form.label :email, 'Email' %> <br>
    <%= form.email_field :email, class: 'form-control' %> <br>
  </div>
  <div class="col-sm-6">
    <%= form.label :first_name, 'First Name' %> <br>
    <%= form.text_field :first_name, class: 'form-control' %> <br>
  </div>
  <div class="col-sm-6">
    <%= form.label :last_name, 'Last Name' %> <br>
    <%= form.text_field :last_name, class: 'form-control' %> <br>
  </div>
  <div class="col-sm-6">
    <%= form.label :role, 'Role' %> <br>
    <% roles_array = User.roles.map { |key, index| [key == 'enduser' ? 'end-user' : key, index] } %>
    <%= form.select(:role, options_for_select(roles_array), {}, { class: 'form-control' }) %>
  </div>

  <div class="col-sm-12 margin-t-sm">
    <%= form.button "Invite User", type: 'submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/invited_users/_list.html.erb
<% if obj.present? %>
  <table class="table">
    <thead>
    <tr>
      <th>Email</th>
      <th>Fists Name</th>
      <th>Last Name</th>
      <th>Accepted</th>
      <th colspan="3">Action</th>
    </tr>
    </thead>

    <tbody>
    <% obj.each do |invited_user| %>
      <tr>
        <td><%= invited_user.email %></td>
        <td><%= invited_user.first_name %></td>
        <td><%= invited_user.last_name %></td>
        <td><%= invited_user.status ? '<span class="text-success">Acceppted</span>'.html_safe : '<span class="text-warning">Invited</span>'.html_safe %></td>
        <td>
          <%= link_to 'Show', invited_user %>
          <%= link_to 'Edit', edit_invited_user_path(invited_user) %>
          <%= link_to 'Destroy', invited_user, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/invited_users/edit.html.erb
<h1>Editing Invited User</h1>

<%= render 'form', invited_user: @invited_user %>

<%= link_to 'Show', @invited_user %> |
<%= link_to 'Back', invited_users_path %>

app/views/invited_users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-sm-12 margin-b-sm">
  <h1>Invited Users</h1>
</div>
<div class="col-sm-12">
  <%= render partial: 'list', locals: { obj: @invited_users } %>
</div>
<br>
<div class="col-sm-12 margin-t-sm">
  <%= link_to 'New Invited User', new_invited_user_path %>
</div>

app/views/invited_users/new.html.erb
<div class="col-sm-12">
  <h1>New Invited User</h1>
</div>
<%= render 'form', invited_user: @invited_user %>
<div class="col-sm-12">
  <%= link_to 'Back', invited_users_path %>
</div>

app/views/invited_users/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert-message text-warning"><%= content_tag :span, value, class: "flash #{key}" %></div>
<% end %>



<%= link_to 'Edit', edit_invited_user_path(@invited_user) %> |
<%= link_to 'Back', invited_users_path %>