config/routes.rb
Rails.application.routes.draw do
  get 'package_trackings/create'

  get 'package_trackings/destroy'

	devise_for :users, controllers: { sessions:      'users/sessions', passwords: 'users/passwords', confirmations: 'users/confirmations',
	                                  registrations: 'users/registrations' }
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	devise_scope :user do
		get '/users/sign_up/:code', to: 'users/registrations#new', as: :sign_up
		# match '/users/:id', to: 'users/registrations#delete_user', via: :delete, as: :delete_user
	end

	root 'package_trackings#track_package'
	resources :invited_users
	resources :packages
  post 'package_trackings/create/:id', to: 'package_trackings#create', as: :package_trackings
	get 'package_trackings/track_package', to: 'package_trackings#track_package', as: :track_package

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlobalIndustry</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand margin-t-sm" href="<%= root_path %>">Global Industry</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav margin-t-sm">
            <% if current_user.admin? || current_user.packager? %>
              <li class="<%= is_active_tab('packages') %>">
                <a href="<%= packages_path %>">Packages <span class="sr-only">(current)</span></a></li>
            <% end %>
            <% if current_user.admin? %>
              <li class="<%= active_class(root_path) %><%= is_active_tab('invited_users') %>">
                <a href="<%= invited_users_path %>">Invited Users</a>
              </li>
            <% end %>

            <li class="<%= active_class(track_package_path) %>"><a href="<%= track_package_path %>">Track Package</a>
            </li>
          </ul>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default pull-right margin-t-c') %>
          <% if current_user.avatar.present? %>
            <div class="ratio img-responsive img-circle" style="background-image: url(<%= current_user.avatar %>);"></div>
          <% else %>
            <div class="ratio img-responsive img-circle" style="background-image: url(<%= '../userprofile.png' %>);"></div>
        <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlobalIndustry</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand margin-t-sm" href="<%= root_path %>">Global Industry</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav" margin-t-sm>
          </ul>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-default pull-right') %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlobalIndustry</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>
</body>
</html>